#!/bin/bash

echo "🔑 Guia para criar o token correto no GitHub:"
echo ""
echo "1. Acesse: https://github.com/settings/tokens"
echo ""
echo "2. Clique em 'Generate new token (classic)'"
echo ""
echo "3. Preencha:"
echo "   - Note: Nova-Language-Push"
echo "   - Expiration: No expiration"
echo ""
echo "4. Selecione estas permissões:"
echo "   ✅ repo (tudo)"
echo "   ✅ workflow"
echo "   ✅ write:packages"
echo "   ✅ admin:repo_hook"
echo ""
echo "5. Clique em 'Generate token'"
echo ""
echo "6. COPIE O TOKEN AGORA! (não vai aparecer depois)"
echo ""
echo "7. Use o token no comando:"
echo "   git push https://SEU_TOKEN@github.com/Marcelinomodz/Nova.git"
echo ""
echo "Exemplo:"
echo "   git push https://github_pat_xxxxxx@github.com/Marcelinomodz/Nova.git"
